import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'SouloSales - See Every Sale. One Dashboard.',
  description: 'Track live deals and countdowns from your favorite brands. Vendors list your sales, shoppers never miss a drop.',
  icons: {
    icon: '/favicon.ico', // Ensure you have a favicon.ico in src/app/
    apple: '/apple-icon.png', // Optional: for Apple devices
  },
  };

  export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* If you're using a font like Inter: */}
      {/* <body className={inter.className}> */}
      <body>
        {children}
        <SharedFooter /> {/* Include your shared footer here */}
      </body>
    </html>
  );
}
